<?php

namespace App\Rules;

use Closure;
use Illuminate\Contracts\Validation\ValidationRule;

class DisposableEmailRule implements ValidationRule
{
    protected array $disposableDomains = [
        // Major disposable email providers
        '10minutemail.com', '10minutemail.net', '10minutemail.org',
        '20minutemail.com', '20minutemail.net',
        '30minutemail.com', '30minutemail.net',
        'guerrillamail.com', 'guerrillamail.net', 'guerrillamail.org', 'guerrillamail.biz', 'guerrillamail.info',
        'tempmail.com', 'tempmail.net', 'tempmail.org', 'temp-mail.org', 'temp-mail.com',
        'mailinator.com', 'mailinator.net', 'mailinator.org', 'mailinator2.com',
        'yopmail.com', 'yopmail.net', 'yopmail.org', 'yopmail.fr', 'yopmail.gq',
        'trashmail.com', 'trashmail.net', 'trashmail.org', 'trash-mail.com',
        'fakeinbox.com', 'fakeinbox.net',
        'getnada.com', 'getnada.net',
        'maildrop.cc', 'maildrop.email',
        'mohmal.com', 'mohmal.in',
        'throwawaymail.com', 'throwawaymail.org',
        'emailondeck.com',
        'mintemail.com',
        'dispostable.com',
        'spamgourmet.com', 'spamgourmet.net', 'spamgourmet.org',
        'sharklasers.com',
        'grr.la',
        'guerrillamailblock.com',
        'pokemail.net',
        'bccto.me',
        'chacuo.net',
        'cust.in',
        'drdrb.net',
        'emailias.com',
        'emailigo.de',
        'emailmiser.com',
        'emailsensei.com',
        'fatflap.com',
        'frapmail.com',
        'frihost.com',
        'inboxalias.com',
        'kaspop.com',
        'kasmail.com',
        'keepmymail.com',
        'killmail.com',
        'killmail.net',
        'klzlk.com',
        'letmymail.com',
        'lookugly.com',
        'lopl.co.cc',
        'mail15.com',
        'mail2rss.org',
        'mail333.com',
        'mail4trash.com',
        'mailbidon.com',
        'mailblocks.com',
        'mailcatch.com',
        'maileater.com',
        'mailexpire.com',
        'mailfa.tk',
        'mailforspam.com',
        'mailfreeonline.com',
        'mailin8r.com',
        'mailincubator.com',
        'mailme.lv',
        'mailme24.com',
        'mailmetrash.com',
        'mailmoat.com',
        'mailnull.com',
        'mailorg.org',
        'mailrock.biz',
        'mailscrap.com',
        'mailseal.de',
        'mailshell.com',
        'mailsiphon.com',
        'mailtemp.info',
        'mailtome.de',
        'mailtrash.net',
        'mailtv.net',
        'mailtv.tv',
        'mailzi.ru',
        'mbx.cc',
        'mega.zik.dj',
        'meltmail.com',
        'mierdamail.com',
        'mintemail.com',
        'moburl.com',
        'mt2009.com',
        'mt2014.com',
        'mytrashmail.com',
        'nepwk.com',
        'nervmich.net',
        'nervtmich.net',
        'netmails.com',
        'netmails.net',
        'netzidiot.de',
        'neverbox.com',
        'nomail.xl.cx',
        'nomail2me.com',
        'nomorespamemails.com',
        'nospam.ze.tc',
        'nospam4.us',
        'nospamfor.us',
        'nospamthanks.info',
        'nowmymail.com',
        'objectmail.com',
        'obobbo.com',
        'oneoffemail.com',
        'onewaymail.com',
        'online.ms',
        'oopi.org',
        'ordinaryamerican.net',
        'otherinbox.com',
        'ourklips.com',
        'outlawspam.com',
        'ovpn.to',
        'owlpic.com',
        'pancakemail.com',
        'pimpedemail.com',
        'pjjkp.com',
        'politikerclub.de',
        'poofy.org',
        'pookmail.com',
        'privacymate.com',
        'proxymail.eu',
        'prtz.eu',
        'quickinbox.com',
        'rcpt.at',
        'recode.me',
        'recyclemail.dk',
        'regbypass.com',
        'rover.info',
        'royal.net',
        'rppkn.com',
        'rtrtr.com',
        's0ny.net',
        'safe-mail.net',
        'safersignup.de',
        'safetymail.info',
        'sandelf.de',
        'saynotospams.com',
        'selfdestructingmail.com',
        'sendspamhere.com',
        'shiftmail.com',
        'shortmail.net',
        'shut.name',
        'shut.ws',
        'sibmail.com',
        'skeefmail.com',
        'slaskpost.se',
        'slopsbox.com',
        'smellfear.com',
        'snakemail.com',
        'sneakemail.com',
        'sogetthis.com',
        'soodonims.com',
        'spam.la',
        'spam4.me',
        'spamavert.com',
        'spambob.com',
        'spambob.net',
        'spambog.com',
        'spambog.de',
        'spambog.ru',
        'spambox.info',
        'spambox.irishspringrealty.com',
        'spambox.us',
        'spamcannon.com',
        'spamcannon.net',
        'spamcero.com',
        'spamcon.org',
        'spamcorptastic.com',
        'spamcowboy.com',
        'spamcowboy.net',
        'spamcowboy.org',
        'spamday.com',
        'spamex.com',
        'spamfree24.com',
        'spamfree24.de',
        'spamfree24.eu',
        'spamfree24.net',
        'spamfree24.org',
        'spamgourmet.com',
        'spamgourmet.net',
        'spamgourmet.org',
        'spamherelots.com',
        'spamhereplease.com',
        'spamhole.com',
        'spamify.com',
        'spaminator.de',
        'spamkill.info',
        'spaml.com',
        'spaml.de',
        'spammotel.com',
        'spamobox.com',
        'spamoff.de',
        'spamsalad.in',
        'spamslicer.com',
        'spamspot.com',
        'spamthis.co.uk',
        'spamthisplease.com',
        'spamtroll.net',
        'speed.1s.fr',
        'supergreatmail.com',
        'supermailer.jp',
        'suremail.info',
        'teewars.org',
        'teleworm.com',
        'teleworm.us',
        'temp-mail.org',
        'temp-mail.ru',
        'tempail.com',
        'tempalias.com',
        'tempemail.biz',
        'tempemail.co.za',
        'tempemail.com',
        'tempemail.net',
        'tempemail.org',
        'tempinbox.co.uk',
        'tempinbox.com',
        'tempmail.eu',
        'tempmail.it',
        'tempmail.us',
        'tempomail.fr',
        'temporarily.de',
        'temporarioemail.com.br',
        'temporaryemail.net',
        'temporaryforwarding.com',
        'temporaryinbox.com',
        'temporarymail.com',
        'temporarymail.net',
        'temporarymail.org',
        'thanksnospam.info',
        'thankyou2010.com',
        'thisisnotmyrealemail.com',
        'throwawayemailaddress.com',
        'tilien.com',
        'tmailinator.com',
        'tradermail.info',
        'trashdevil.com',
        'trashdevil.de',
        'trashmail.at',
        'trashmail.com',
        'trashmail.de',
        'trashmail.me',
        'trashmail.net',
        'trashmail.org',
        'trashymail.com',
        'trashymail.net',
        'trbvm.com',
        'twinmail.de',
        'tyldd.com',
        'uggsrock.com',
        'uggsrock.net',
        'uggsrock.org',
        'uggsrock.us',
        'upliftnow.com',
        'uplipht.com',
        'venompen.com',
        'veryrealemail.com',
        'viditag.com',
        'viewcastmedia.com',
        'viewcastmedia.net',
        'viewcastmedia.org',
        'vomitmail.com',
        'vomitmail.net',
        'vpn.st',
        'walkmail.net',
        'walkmail.ru',
        'webemail.me',
        'wegwerfmail.de',
        'wegwerfmail.net',
        'wegwerfmail.org',
        'wetrainbayarea.com',
        'wetrainbayarea.org',
        'wh4f.org',
        'whyspam.me',
        'willselfdestruct.com',
        'winemaven.info',
        'wronghead.com',
        'wuzup.net',
        'wuzupmail.net',
        'wwwnew.eu',
        'xagloo.com',
        'xemail.com',
        'xents.com',
        'xmaily.com',
        'xoxy.net',
        'yep.it',
        'yogamaven.com',
        'yopmail.com',
        'yopmail.net',
        'yopmail.org',
        'yopmail.fr',
        'yopmail.gq',
        'yopmail.ml',
        'yopmail.tk',
        'yourdomain.com',
        'yuurok.com',
        'z1p.biz',
        'ze.tc',
        'zeepost.nl',
        'zetmail.com',
        'zoemail.net',
        'zoemail.org',
        // Patterns for subdomain-based disposable services
        'mailnesia.com',
        'mailcatch.com',
        'guerrillamailblock.com',
        'spam4.me',
    ];

    public function validate(string $attribute, mixed $value, Closure $fail): void
    {
        $domain = strtolower(strrchr($value, '@'));
        $domain = ltrim($domain, '@');

        if (in_array($domain, $this->disposableDomains, true)) {
            $fail(__('This email domain is not allowed. Please use a permanent email address.'));
        }

        // Also check for subdomain patterns (e.g., something@tempmail.com)
        foreach ($this->disposableDomains as $disposableDomain) {
            if (str_ends_with($domain, '.'.$disposableDomain) || $domain === $disposableDomain) {
                $fail(__('This email domain is not allowed. Please use a permanent email address.'));
                return;
            }
        }
    }
}